import { Alert } from "../types/alert";

export const mockAlerts: Alert[] = [
  {
    id: "a1",
    name: "High Temperature - Tel Aviv",
    location: "Tel Aviv",
    latitude: 32.0853,
    longitude: 34.7818,
    parameter: "temperature",
    condition: "greaterThan",
    threshold: 35,
    unit: "°C",
    state: "triggered",
    isTriggered: true,
    createdAt: "2025-04-20T09:00:00Z",
    triggeredAt: "2025-04-28T08:15:00Z",
    clearedAt: undefined,
    lastChecked: new Date().toISOString(),
  },
  {
    id: "a2",
    name: "Rain Alert - London",
    location: "London",
    latitude: 51.5072,
    longitude: -0.1276,
    parameter: "precipitation",
    condition: "greaterThan",
    threshold: 10,
    unit: "mm",
    state: "clear",
    isTriggered: false,
    createdAt: "2025-04-25T12:00:00Z",
    triggeredAt: undefined,
    clearedAt: "2025-04-27T16:00:00Z",
    lastChecked: new Date().toISOString(),
  },
  {
    id: "a3",
    name: "Wind Speed Watch - Chicago",
    location: "Chicago",
    latitude: 41.8781,
    longitude: -87.6298,
    parameter: "windSpeed",
    condition: "greaterThan",
    threshold: 20,
    unit: "m/s",
    state: "disabled",
    isTriggered: false,
    createdAt: "2025-04-15T07:45:00Z",
    triggeredAt: undefined,
    clearedAt: undefined,
    lastChecked: new Date().toISOString(),
  },
  {
    id: "a4",
    name: "Low Visibility - Berlin",
    location: "Berlin",
    latitude: 52.52,
    longitude: 13.405,
    parameter: "visibility",
    condition: "lessThan",
    threshold: 2,
    unit: "km",
    state: "clear",
    isTriggered: false,
    createdAt: "2025-04-22T10:00:00Z",
    triggeredAt: undefined,
    clearedAt: undefined,
    lastChecked: new Date().toISOString(),
  },
];
